import A from '../../src/assets/sign-language-alphabets/1.png'
import B from '../../src/assets/sign-language-alphabets/2.png'
import C from '../../src/assets/sign-language-alphabets/3.png'
import D from '../../src/assets/sign-language-alphabets/4.png'
import E from '../../src/assets/sign-language-alphabets/5.png'
import F from '../../src/assets/sign-language-alphabets/6.png'
import G from '../../src/assets/sign-language-alphabets/7.png'
import H from '../../src/assets/sign-language-alphabets/8.png'
import I from '../../src/assets/sign-language-alphabets/9.png'
import J from '../../src/assets/sign-language-alphabets/10.png'
import K from '../../src/assets/sign-language-alphabets/11.png'
import L from '../../src/assets/sign-language-alphabets/12.png'
import M from '../../src/assets/sign-language-alphabets/13.png'
import N from '../../src/assets/sign-language-alphabets/14.png'
import O from '../../src/assets/sign-language-alphabets/15.png'
import P from '../../src/assets/sign-language-alphabets/16.png'
import Q from '../../src/assets/sign-language-alphabets/17.png'
import R from '../../src/assets/sign-language-alphabets/18.png'
import S from '../../src/assets/sign-language-alphabets/19.png'
import T from '../../src/assets/sign-language-alphabets/20.png'
import U from '../../src/assets/sign-language-alphabets/21.png'
import V from '../../src/assets/sign-language-alphabets/22.png'
import W from '../../src/assets/sign-language-alphabets/23.png'
import X from '../../src/assets/sign-language-alphabets/24.png'
import Y from '../../src/assets/sign-language-alphabets/25.png'
import Z from '../../src/assets/sign-language-alphabets/26.png'

export const imgArray=[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z];